[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
    source $XDG_CONFIG_HOME/nvim/plugin_settings/deoplete.vim
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1
depends = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1
depends = ['deoplete.nvim']
[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1
hook_add = 'let g:necosyntax#min_keyword_length = 2'
depends = ['deoplete.nvim']
# Completion for specified Language.
[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_i = 1
[[plugins]]
repo = 'Shougo/neco-vim'
on_i = 1
on_ft = 'vim'
depends = ['deoplete.nvim']
[[plugins]]
repo = 'Rip-Rip/clang_complete'
on_ft = ['C', 'C++']
on_i = 1
depends = ['deoplete.nvim']
[[plugins]]
repo = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
on_i = 1

# SuperTab
[[plugins]]
repo = "ervandew/supertab"

# Gundo
[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = ['MundoToggle']
hook_add = '''
    nnoremap <Space>m :MundoToggle<CR>
'''

# TaskList
[[plugins]]
repo = 'vim-scripts/TaskList.vim'
on_map = ['<Plug>TaskList']
hook_add = '''
    nmap <Space>T <Plug>TaskList
'''
# FileType Extention
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
    set rtp+=$GOPATH/src/github.com/golang/lint/misc/vim
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_structs = 1
    let g:go_highlight_interfaces = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_build_constraints = 1

    let g:go_fmt_command = 'goimports'
    let s:goargs = go#package#ImportPath(expand('%:p:h'))
    let g:neomake_go_errcheck_maker = {
        \ 'args': ['-abspath', s:goargs],
        \ 'append_file': 0,
        \ 'errorformat': '%f:%l:%c:\ %m, %f:%l:%c\ %#%m',
        \ }
    let g:neomake_go_enabled_makers = ['golint', 'govet', 'errcheck']
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ["python", "python3", "djangohtml"]
[[plugins]]
repo = 'hdima/python-syntax'
on_ft = ["python", "python3", "djangohtml"]

[[plugins]]
repo = 'vim-pandoc/vim-pandoc'
on_ft = ["text", "pandoc", "markdown", "rst", "textile"]

[[plugins]]
repo = 'keith/tmux.vim'
on_ft = ["tmux"]

[[plugins]]
repo = "c01o/previm"
on_ft = ['markdown']

