# Deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
    source $XDG_CONFIG_HOME/nvim/plugin_settings/deoplete.vim
    set shortmess+=c
    autocmd CompleteDone * pclose!
'''
on_i = 1
[[plugins]]
repo = 'Shougo/echodoc.vim'
depends = ['deoplete.nvim']
hook_add = '''
    set cmdheight=2
    let g:echodoc_enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ["python", "python3", "djangohtml"]
on_i = 1
hook_source = '''
    let g:deoplete#sources#jedi#show_docstring=0
'''

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
depends = ['deoplete.nvim']
on_ft = ['ruby', 'eruby']

[[plugins]]
repo = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
build = 'make'
on_ft = 'go'
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = expand("$GOPATH/bin/gocode")
    let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
    let g:deoplete#sources#go#use_cache = 0
    let g:deoplete#sources#go#json_directory = expand('~/.cache/deoplete/go/$GOOS_$GOARCH')
    let g:deoplete#sources#go#pointer = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
    if has('conceal')
        set conceallevel=2 concealcursor=niv
    endif
'''
on_i = 1
depends = ['neosnippet-snippets']
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1
[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1
depends = ['deoplete.nvim']
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1
depends = ['deoplete.nvim']
[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1
hook_add = 'let g:necosyntax#min_keyword_length = 2'
depends = ['deoplete.nvim']
# Completion for specified Language.
[[plugins]]
repo = 'Shougo/neco-vim'
on_i = 1
on_ft = 'vim'
depends = ['deoplete.nvim']
[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['C', 'C++']
on_i = 1
depends = ['deoplete.nvim']
hook_add = '''
let g:deoplete#sources#clang#libclang_path = "/usr/local/Cellar/llvm/3.9.1/lib/libclang.dylib"
let g:deoplete#sources#clang#clang_header = "/usr/local/Cellar/llvm/3.9.1"
'''
[[plugins]]
repo = "zplug/vim-zplug"
on_ft = ['zplug']

# SuperTab
[[plugins]]
repo = "ervandew/supertab"

# Mundo
[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = ['MundoToggle']
hook_add = '''
    nnoremap <Space>m :MundoToggle<CR>
'''

# TaskList
[[plugins]]
repo = 'vim-scripts/TaskList.vim'
on_map = ['<Plug>TaskList']
hook_add = '''
    nmap <Space>T <Plug>TaskList
'''
# FileType Extention
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
    set rtp+=$GOPATH/src/github.com/golang/lint/misc/vim
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_structs = 1
    let g:go_highlight_interfaces = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_build_constraints = 1
    let g:go_template_autocreate = 0

    let g:go_fmt_command = 'goimports'
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ["python", "python3", "djangohtml"]
[[plugins]]
repo = 'hdima/python-syntax'
on_ft = ["python", "python3", "djangohtml"]

[[plugins]]
repo = 'keith/tmux.vim'
on_ft = ["tmux"]

[[plugins]]
repo = "plasticboy/vim-markdown"
on_ft = ['markdown', 'md']
hook_source = '''
    let g:vim_markdown_folding_disabled = 1
'''
[[plugins]]
repo = 'vim-pandoc/vim-pandoc'
on_ft = ["text", "pandoc", "markdown", "rst", "textile"]
hook_source = '''
    let g:pandoc#filetypes#handled = ["pandoc", "markdown"]
    set nospell
    let g:pandoc#modules#disabled = ["folding"]
    let g:pandoc#spell#enabled = 0

    let g:pandoc#filetypes#pandoc_markdown = 0
'''
[[plugins]]
repo = 'vim-pandoc/vim-pandoc-syntax'
on_ft = ["text", "pandoc", "markdown", "rst", "textile"]

[[plugins]]
repo = "c01o/previm"
on_ft = ['markdown', "md"]
hook_source = '''
    let g:previm_open_cmd = 'open -a Google\ Chrome'
'''

[[plugins]]
repo = "mattn/emmet-vim"
on_ft = ["html"]

[[plugins]]
repo = "tpope/vim-endwise"
on_ft = ["zsh", "ruby", "c", "cpp"]
