# Manage Plugins.
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'haya14busa/dein-command.vim'
# Vim process manager.
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
    if dein#util#_is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''
# VimShell
[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
    let g:deol#prompt_patter = '% \|%$'
'''
[[plugins]]
repo = 'rhysd/migemo-search.vim'

# Vim Trailing WhiteSpace
# 行末の半角スペースを可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    let g:extra_whitespace_ignored_filetypes = ['denite', 'mkd', 'md', 'Mundo', 'MundoDiff']
'''
# Expand status line.
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/plugin_settings/lightline.vim
'''
# コメントアウトしたい範囲を選択して、
# [Leader]xでコメントアウト
[[plugins]]
repo = 'hrp/EnhancedCommentify'
# Tcomment_vim
# コメントON/OFFを手軽に実行
[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = "nathanaelkane/vim-indent-guides"
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/plugin_settings/vim_indent_guides.vim
'''

[[plugins]]
repo = "Konfekt/FastFold"

# Run editing code in Vim.
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  # let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
    let g:quickrun_config = {'_': {'hook/time/enable': '1', 'runner': "vimproc", 'runner/vimproc/updatetime': '40'},}
'''
hook_add = '''
    nnoremap <Space>r :QuickRun<CR>
    let g:quickrun_config = {
    \ "_": {
    \   "outputter/buffer/close_on_empty" : 1,
    \   "outputter/buffer/split" : ":vertical rightb",
    \   "runner" : "vimproc",
    \   "runner/vimproc/updatetime" : 60,
    \ },
    \ "C++":{
    \   "type": "C++",
    \   "command" : "clang++ -std=C++11",
    \ }}
    nnoremap <expr><silent>> <C-c> quickrun#is_runnning() ? quickrun#sweep_sessions() : "\<C-c>"
'''

# Japanese Doc for Vim.
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'

# AutoSave
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
    " デフォルトで無効にする
    let g:auto_save = 0
    " do not save while in insert mode
    let g:auto_save_in_insert_mode = 0
    nmap [toggle]S :AutoSaveToggle<CR>
'''

# Tagbar
[[plugins]]
repo = "majutsushi/tagbar"
hook_add = '''
    nmap <Space>t :TagbarToggle<CR>
'''

# Change FT relfecting Context.
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Template for FT.
[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/plugin_settings/sonictemplate.vim
'''

# Outliner for vim.
[[plugins]]
repo = 'vim-scripts/VOoM'

# Unite.vim for nvim.
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/plugin_settings/denite.vim
'''
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/neoyank.vim'

# Git implemnent for vim.
[[plugins]]
repo = 'mattn/gist-vim'
depends = ['mattn/webapi-vim']
[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'gregsexton/gitv'
depends = 'tpope/vim-fugitive'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/plugin_settings/neomake.vim
'''

# Editing Text Enhancer.
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'vim-scripts/Align'
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'kana/vim-textobj-line'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'vim-scripts/YankRing.vim'
hook_source = '''
let g:yankring_history_dir = '~/.cache/'
let g:yankring_max_history = 10000
'''

# Color Schemes
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'croaker/mustang-vim'
[[plugins]]
repo = 'jeffreyiacono/vim-colors-wombat'
[[plugins]]
repo = 'nanotech/jellybeans.vim'
[[plugins]]
repo = 'vim-scripts/Lucius'
[[plugins]]
repo = 'vim-scripts/Zenburn'
[[plugins]]
repo = 'mrkn/mrkn256.vim'
[[plugins]]
repo = 'jpo/vim-railscasts-theme'
[[plugins]]
repo = 'therubymug/vim-pyte'
[[plugins]]
repo = 'tomasr/molokai'
# ColorSchemes End.


